-keep class com.android.androidexpert.** { *; }

# Keep the binding classes generated by ViewBinding
-keep class **ViewBinding { *; }

# Keep the binding classes generated by DataBinding
-keep class **.databinding.* { *; }
-keep class **.databinding.DataBinderMapperImpl { *; }

# Keep the ViewBinding class and all inner classes
-keep class **ViewBinding { *; }
-keepclasseswithmembers class * {
    *** getBinding (...);
}

# Keep SQL Cipher
-keep class net.sqlcipher.** { *; }
-keep class net.sqlcipher.database.** { *; }

# AndroidX Room
-keep class androidx.room.** { *; }
-keep interface androidx.room.** { *; }

# AndroidX SQLite
-keep class androidx.sqlite.** { *; }
-keep interface androidx.sqlite.** { *; }

# Dagger
-keep class dagger.** { *; }
-keep class javax.inject.** { *; }
-keep class * extends dagger.internal.*

# Hilt
-keep class androidx.hilt.** { *; }
-keep interface androidx.hilt.** { *; }

# Retrofit
-keepattributes Signature, InnerClasses, EnclosingMethod
-keepattributes RuntimeVisibleAnnotations, RuntimeVisibleParameterAnnotations
-keepclassmembers,allowshrinking,allowobfuscation interface * {
    @retrofit2.http.* <methods>;
}
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
-dontwarn javax.annotation.**
-dontwarn kotlin.Unit
-dontwarn retrofit2.KotlinExtensions
-dontwarn retrofit2.KotlinExtensions$*
-if interface * { @retrofit2.http.* <methods>; }
-keep,allowobfuscation interface <1>

# OkHttp
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn javax.annotation.**
-keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase

# Gson
-keepattributes Signature
-keepattributes *Annotation*
-dontwarn sun.misc.**
-keep class com.google.gson.** { *; }
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

# Glide
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep class * extends com.bumptech.glide.module.AppGlideModule {
 <init>(...);
}
-keep public enum com.bumptech.glide.load.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}
-keep class com.bumptech.glide.load.data.ParcelFileDescriptorRewinder$InternalRewinder {
  *** rewind();
}

# Coroutines
-keepnames class kotlinx.coroutines.internal.MainDispatcherFactory {}
-keepnames class kotlinx.coroutines.CoroutineExceptionHandler {}

# Paging
-keep class androidx.paging.** { *; }

# Shimmer
-keep class com.facebook.shimmer.** { *; }

# General Android
-keepclassmembers class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator CREATOR;
}

# Keep custom model classes
-keep class your.package.name.models.** { *; }
